development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: xxxdb_dev
  pool: 5
  username: testuser
  password: testuser
test: &test
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: xxxdb_test
  pool: 5
  username: testuser
  password: testuser

cucumber:
  <<: *test
